OrdererOrgs:
  - Name: Orderer
    Domain: tfgalbertous.com
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
PeerOrgs:
  - Name: Org1
    Domain: org1.tfgalbertous.com
    Template:
      Count: 3
      SANS:
        - localhost
    Users:
      Count: 1
